### ISSUE TITLE
Please add adjustable hotkey settings

### ISSUE THREAD

**Issue by ChuckSavage** [mbakulin/ltn_screensaver#1]
You can't have your mod installed and try running with ctrl+s key to drop items You end up activating the screen saver. I need to come up with a different key, than a movement key.

**Comment by mbakulin** [comment]
Did you get the mod from factorio mod portal? As far as I remember, hotkeys can already be adjusted via game settings (settings - controls - scroll down to mods)

**Comment by ChuckSavage** [comment]
Alright - strange - when I first had the mod loaded, I checked there first and hadn't seen it. Just loaded it again now, and the settings are there. Thanks, and sorry for the bother.
